name: Test PR

on:
  pull_request_target:
  workflow_call:
  workflow_dispatch:

jobs:
  test-protocol-with-repo-variables:
    if: ${{ vars.USE_CUSTOM_VARIABLES == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repository
        uses: actions/checkout@v4
      - name: Test evaluation
        run: |
            chmod +x ./tests/setup_and_run.sh
            export PROTOCOL=${{vars.PROTOCOL}} && ./tests/setup_and_run.sh
  test-protocol-with-env-variables:
    if: ${{ vars.USE_CUSTOM_VARIABLES != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repository
        uses: actions/checkout@v4
      - name: Test evaluation
        run: |
            chmod +x ./tests/setup_and_run.sh
            source env.sh && ./tests/setup_and_run.sh
